openid :
# store       :  filesystem
# location    :  /tmp

  store       :  memcache
  location    :  127.0.0.1:11211
  key_prefix  :  dlt-openid


cache :
  store       :  memcache
  location    :  127.0.0.1:11211
  key_prefix  :  dlt-openid
